FROM python:3.9

EXPOSE 5000

COPY . /workflow-inference-compiler
WORKDIR /workflow-inference-compiler

# RUN pip3 install -r requirements.txt
RUN pip3 install -e ".[restapi]"

CMD ["uvicorn", "api:app", "--host" ,"0.0.0.0", "--port", "5000"]
